const Crypto = require('../models/Crypto')

exports.getOneCrypto = (cryptoId) => Crypto.findById(cryptoId)
exports.getAllCryptos = () => Crypto.find()
exports.getLastAdded = () => Crypto.find({}).sort({createdAt: -1})
exports.update = (cryptoId, data) => Crypto.findByIdAndUpdate(cryptoId, data, {runValidators: true})
exports.deleteCrypto = (cryptoId) => Crypto.findByIdAndDelete(cryptoId, {runValidators: true})
exports.getSearchedby = (item, method) => Crypto.find({}).where('method').equals(`${method}`)
                                                             .where('name').equals(`${item}`)
exports.createNewCrypto = (data) => Crypto.create(data)
